[package]
name = "cqrs-es2"
version = "0.2.0"
authors = [
  "Dave Garred <dave.garred@serverlesstechnology.com>",
  "Bassem Girgis <brgirgis@gmail.com>",
]
edition = "2018"
license-file = "LICENSE"
keywords = ["cqrs", "event-sourcing", "serverless", "lambda"]
description = "A lightweight, opinionated CQRS and event sourcing framework targetting serverless architectures."
documentation = "https://docs.rs/cqrs-es2"
repository = "https://github.com/brgirgis/cqrs"
readme = "README.md"

[dependencies]
serde = { version = "^1.0.127", features = ["derive"] }
serde_json = "^1.0.66"

[dev-dependencies]
static_assertions = "0.3"
uuid = { version = "0.8.2", features = ["v4"] }
